#ifndef _avcodecid_h_
#define _avcodecid_h_

typedef enum AVPACKET_CODEC_ID
{
	AVCODEC_NONE = 0x00,

	AVCODEC_VIDEO_MPEG1,
	AVCODEC_VIDEO_MPEG2,
	AVCODEC_VIDEO_MPEG4,
	AVCODEC_VIDEO_H264,
	AVCODEC_VIDEO_H265,
	AVCODEC_VIDEO_H266,
	AVCODEC_VIDEO_VP8,
	AVCODEC_VIDEO_VP9,
	AVCODEC_VIDEO_AV1,
	AVCODEC_VIDEO_AVS,
	AVCODEC_VIDEO_SVAC,

	AVCODEC_IMAGE_PNG = 0x100,
	AVCODEC_IMAGE_GIF,
	AVCODEC_IMAGE_BMP,
	AVCODEC_IMAGE_JPEG,

	AVCODEC_AUDIO_PCM = 0x10000,
	AVCODEC_AUDIO_G711A, // G711 alaw
	AVCODEC_AUDIO_G711U, // G711 ulaw
	AVCODEC_AUDIO_G719,
	AVCODEC_AUDIO_G726,
	AVCODEC_AUDIO_G729,
	AVCODEC_AUDIO_MP3,
	AVCODEC_AUDIO_AAC,
	AVCODEC_AUDIO_AC3,
	AVCODEC_AUDIO_OPUS,
	AVCODEC_AUDIO_MP2, // MPEG-2 Layer II
	AVCODEC_AUDIO_SPEEX,
	AVCODEC_AUDIO_SVAC,

	AVCODEC_TEXT_WEBVTT = 0x20000,
	AVCODEC_TEXT_SRT,
	AVCODEC_TEXT_CC,

	AVCODEC_DATA_RAW = 0x30000,
	AVCODEC_DATA_MP2P, // MPEG-2 PS
	AVCODEC_DATA_MP2T, // MPEG-2 TS
} AVPACKET_CODEC_ID;

#endif /* !_avcodecid_h_ */
